### ISSUE TITLE
AttributeError: 'str' object has no attribute 'trim'

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-test-suite#10]
```
Traceback (most recent call last):
   File "./bin/compare_images.py", line 93, in <module>
     writeResult(name, key, info[key], error.trim(), float('inf'));
AttributeError: 'str' object has no attribute 'trim'
```

Seeing this running tests in Node.js bindings, causes the `compare_images.py` script to exit.

/cc @mapbox/gl

**Comment by Yashpandey4** [comment]
To those still looking for an answer, the correct function is "strip()"

**Comment by lox-enterprises** [comment]
> To those still looking for an answer, the correct function is "strip()"

Thanks for adding that, six years later @Yashpandey4 :-)

Google brought me here, I guess it's a common mistake for people writing both in Python and in JavaScript: `trim()` is what you'd do in JavaScript vs. Python's `strip()`.
