### ISSUE TITLE
Support arbitrary test heirarchy

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-test-suite#102]
There is currently a fixed test hierarchy: `[style property name]/[style property value]`. This system has not scaled elegantly as we've added tests for other sorts of things: tile extents, regression tests, query tests, etc. 
- [ ] refactor to allow for an arbitrary test hierarchy
- [ ] organize existing tests into a new-and-improved heirarchy
- [ ] refactor query tests to use the operations API and merge them into the new hierarchy

**Comment by amyleew** [comment]
This sounds great @lucaswoj! It'd be useful when storing similar type tests like, [geojson's nested here](https://github.com/mapbox/mapbox-gl-test-suite/tree/master/render-tests/geojson)

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/3920
