### ISSUE TITLE
test transitions

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-test-suite#116]
We should to figure out how to add tests for property transitions, in order to prevent bugs like:
- https://github.com/mapbox/mapbox-gl-js/issues/2762
- https://github.com/mapbox/mapbox-gl-js/issues/2769

A prerequisite for this is that the test harness has control over the clock used for rendering transitions, so it can deterministically render, say, 50% of the way through a transition. Then we could add that percentage as a parameter somewhere in the test case metadata.

**Comment by jfirebaugh** [comment]
gl-js internals which use `Date.now()` directly that need to be converted to using a passed in parameter.

* https://github.com/mapbox/mapbox-gl-js/blob/062f52d836e8991f694c6742ab24ecfdc643151b/js/style/style_declaration.js#L53-L53
* https://github.com/mapbox/mapbox-gl-js/blob/8eaeebbcaeea012fe7876c06fb558a0a2ea99475/js/style/style_transition.js#L54-L54
* https://github.com/mapbox/mapbox-gl-js/blob/8eaeebbcaeea012fe7876c06fb558a0a2ea99475/js/style/style_layer.js#L311-L311
* https://github.com/mapbox/mapbox-gl-js/blob/1df146627092b58c8db64d45530c74cd12a3fa02/js/render/frame_history.js#L17-L17
* https://github.com/mapbox/mapbox-gl-js/blob/7840d9c2265c1d9be52a329d9a9c38784b75b3ca/js/style/style.js#L250-L257

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/3912
