### ISSUE TITLE
Testing glyph rendering capacity for CJK fonts

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-gl-test-suite#126]
To test glyph texture size (currently `1024x1024`) to ensure it's large enough to render a kind of "worst case scenario" (that is still realistic) china mapview. We're simulating stress tests of displaying CJK characters. 

@xrwang and I worked on the [inital rendering test](https://github.com/mapbox/mapbox-gl-test-suite/blob/china-tests/data/bbox.geojson) which maxed out point and character density, and it failed, as expected. The second test case should reflect what could realistically represent the text diversity/density of a china map view.

### Setup

- Install GL JS
- Run the render test suite and run it targeting a specific test (https://github.com/mapbox/mapbox-gl-js/blob/master/CONTRIBUTING.md#running-tests)
- Check out the first test
  - [cjk-fonts/literal/style.json](https://github.com/mapbox/mapbox-gl-test-suite/blob/65a7b7f5ee7ed5eb2f1742fc128745598adfbca7/render-tests/cjk-fonts/literal/style.json)
  - [cjk-fonts/literal/expected.png](https://github.com/mapbox/mapbox-gl-test-suite/blob/65a7b7f5ee7ed5eb2f1742fc128745598adfbca7/render-tests/cjk-fonts/literal/expected.png)
- Pull [`china-test` branch](https://github.com/mapbox/mapbox-gl-test-suite/tree/china-tests) of the GL test suite repo & npm link it into place with GL JS
- Craft a glyph overflow test. Suggestions:
  - Use an inline geojson source (https://github.com/mapbox/mapbox-gl-test-suite/blob/master/render-tests/geojson/inline-feature/style.json)
  - You'll probably want to script the creation of your inline geojson. E.g. something that iterates through N CJK characters, creates a point per character randomly within the render test viewport'

In theory there should be a test that should push GL JS to its very limit of glyph atlas space. Then we'll want to see if native can pass the test (probably not, GL Native should behave exactly like GL JS) and work toward parity. (per @yhahn)

### Background

- https://github.com/mapbox/mapbox-gl-js/issues/141

## Next steps

- [ ] Estimate count of distinct glyphs in text dense location on the baidu map 
- [ ] Craft a test(s) to simulate this density

@mapbox/cartography-cats

**Comment by bhousel** [comment]
> To test glyph texture size (currently 1024x1024) to ensure it's large enough to render a kind of "worst case scenario" (that is still realistic) china mapview. We're simulating stress tests of displaying CJK characters.

1024x1024 is not large enough to render a "worst case scenario".. You can load a lot of glyphs at z10, and 60degree tilt to load more tiles on the screen, then pan around a little bit.

see https://github.com/mapbox/mapbox-gl-js/pull/1923#issuecomment-171074882

"I have been testing around this location in Southern China: # 10.01/22.9452/113.1932 - set tilt to maximum to load as many tiles as possible, and scroll around. It does take a LOT of scrolling to get to 2048x2048, and even textures larger than that are considered safe for WebGL."

**Comment by amyleew** [comment]
## Results

These two tests for character count rendering used Chinese Streets data on a sample map, only plotting road labels, pois, and place_labels. [Tests are both passing](https://github.com/mapbox/mapbox-gl-test-suite/tree/china-tests/render-tests/cjk-fonts) possibly because the range of 700 or 1350 characters are not solely Chinese characters. The [Noto CJK SC font](https://www.google.com/get/noto/help/cjk/) contains all four languages characters: S Chinese, T Chinese, Japanese and Korean and the languages are mixed together in the `unicode` range as well. 


### Test 1

Test 1 used generated [bbox-test1.geojson](https://github.com/mapbox/mapbox-gl-test-suite/blob/1b07e3d76ed1c752a53e8dcacb36d0caad6d5ad9/data/bbox1.geojson) with roughly 86 points testing about 700 characters. 

![image](https://cloud.githubusercontent.com/assets/4587826/17119441/ee801b66-5293-11e6-9388-5c12f10745c2.png)


### Test 2

Test 2 used generated [bbox-test2.geoson](https://github.com/mapbox/mapbox-gl-test-suite/blob/1b07e3d76ed1c752a53e8dcacb36d0caad6d5ad9/data/bbox2.geojson) with roughly 139 points and 1350 characters.

![image](https://cloud.githubusercontent.com/assets/4587826/17119456/0921e242-5294-11e6-939c-83b810deda27.png)


## Next steps

Instead of grabbing the _assumed_ range of Chinese characters, like I did with these tests... Test 1 was 385 to 1085 and Test 2 was 385 to 1735 .... @xrwang and I are looking to approach this differently and either find reliable way to only test Chinese characters, possibly using online sources for [CJK table data](https://en.wikipedia.org/wiki/List_of_CJK_Unified_Ideographs,_part_1_of_4). Then run the two tests again with only Chinese characters being rendered.

Or, can we change the way gl makes that spritesheet of glyphs / the glyph atlas? Maybe it doesn't make sense to grab the `256` characters surrounding the character when working with non-Latin fonts? If that is even an option.

/cc @yhahn

**Comment by xrwang** [comment]
echoing @amyleew's comment, we're finding the unicode ranges for cjk, and just SC (simplified chinese) are bit complicated. 

We want to figure out if, on GL / fontnik, when the font stack goes from pbf ---> sdf ---> texture, it can be selective aka we can have more control over which characters end up on the glyph texture. From tests / the way the table is arranged, https://en.wikipedia.org/wiki/List_of_CJK_Unified_Ideographs,_part_1_of_4 since the numerical sequence is by radical and not by frequency of use, we actually don't need entire ranges of characters from the font, only intermittent ones. Ie, instead of putting an entire range of characters, 0-6000 on the glyph texture, could the current set up work with putting 0-40, value 1000, value 1234, value 1568, etc ?

**Comment by friedbunny** [comment]
“Frequency of use” may be a deceiving metric if it’s based on written-use, rather than use in place names. In Japan, at least, there are places that use very uncommon characters in their names.

I couldn’t find a good list of rare-character names, but [this list](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Japan/Place_names_with_unusual_readings) has some discussion of unusual place name readings and bit on the use of obsolete, non-[jōyō kanji](https://en.wikipedia.org/wiki/Jōyō_kanji).

**Comment by amyleew** [comment]
## Glyph atlas

Per chat w/ @nickidlugash @xrwang, we're looking to examine the `glyph atlas` itself. The entire atlas can fit up to `1024` characters based on my [test China map](https://api.mapbox.com/styles/v1/mslee/ciqya11y80005bikpss7m23zf.html?title=true&access_token=pk.eyJ1IjoibXNsZWUiLCJhIjoiclpiTWV5SSJ9.P_h8r37vD8jpIH1A6i1VRg#17.64/31.29743/120.57328), I counted about `900` CJK characters on a full glyph atlas.

I was able to get a `900` test passing with a slight diff, but I'd like to test these [geojson files](https://github.com/mapbox/mapbox-gl-test-suite/tree/china-tests/data) in Studio to compare the glyph atlas files they produce.

![download 1](https://cloud.githubusercontent.com/assets/4587826/17150225/9c52effe-533c-11e6-8b5b-d4d374442c4b.png)

## Next steps

Take these tests into Studio to visualize the glyph atlas and see:

1. When the atlas fills up
2. What it does / how it renders when the atlas is full

**Comment by mikemorris** [comment]
> We want to figure out if, on GL / fontnik, when the font stack goes from pbf ---> sdf ---> texture, it can be selective aka we can have more control over which characters end up on the glyph texture.

@xrwang @friedbunny The only glyphs that should end up in the glyph atlas are those that will actually be needed to render labels - we may download many more because of the way we split glyph ranges into PBFs, but that's a separate problem from glyph atlas overflow that I started exploring a while ago in https://github.com/mapbox/node-fontnik/issues/36

**Comment by bhousel** [comment]
Yes, echoing everything @mikemorris said above... Also the actual atlas texture layout can depend on which tiles happen to load before which other tiles.  (This happens asynchronously).

**Comment by lucaswoj** [comment]
Closed by #131
