### ISSUE TITLE
Add regression test for extrusions causing other fills to render wrong color

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-test-suite#159]
(Issue fixed in https://github.com/mapbox/mapbox-gl-js/pull/3548 — because of the way we are now drawing backgrounds, calling `clearColor` in extrusions was causing other fill layers to render the wrong color.)

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/3914
