### ISSUE TITLE
Add tests for transition properties

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-test-suite#168]
Per https://github.com/mapbox/mapbox-gl-style-spec/issues/171, let's add tests for transition properties. Sticking point is somehow taking a screenshot after a certain elapsed time: @lucaswoj pointed me to a [wait operation](https://github.com/mapbox/mapbox-gl-test-suite/blob/a0b0e3be927dff9a01b0869a4d0b41c830370388/render-tests/runtime-styling/filter-default-to-false/style.json#L7-L19) that waits til rendering is complete, but it [doesn't support a duration argument yet](https://github.com/mapbox/mapbox-gl-js/blob/95b0ca42bf8376561db7e96c616d76696d8f65f7/test/suite_implementation.js#L83-L102).

- [ ] extend `wait` to include a duration parameter in `gl-js`
- [ ] add tests with durations to test transitions

**Comment by jfirebaugh** [comment]
Previously: #116

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/3912
