### ISSUE TITLE
Add tests for (implicit) refs + data-driven paint properties

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-test-suite#197]
Add a test that verifies that even when multiple layers share a layout vertex buffer, they still get distinct paint vertex buffers. I just noticed that https://github.com/mapbox/mapbox-gl-native/pull/7372 doesn't handle this correctly.

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/3910
