### ISSUE TITLE
Use multiple reference images

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-test-suite#25]
When comparing the actual images with our reference images, we're always going to have discrepancies because OpenGL isn't specified well enough to achieve pixel perfect output. The renderers we're using are all different; even when rendering on OS X, the result depends on the GPU in your machine.

To account for this, we should add multiple reference images per test and use the match that is closest to decide test outcome.

refs #24 cc @ansis @jfirebaugh

**Comment by jfirebaugh** [comment]
Sounds good to me. Let's be careful when adding additional images to distinguish between acceptable discrepancies and actual rendering bugs though -- some of the current discrepancies between actual and expected images are legitimate rendering bugs.

**Comment by jfirebaugh** [comment]
Looks like this won't be necessary with pixelmatch.
