### ISSUE TITLE
Unreadable test titles

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-test-suite#47]
Some test titles appear white on white for some reason:

![image](https://cloud.githubusercontent.com/assets/25395/10372334/fde09ab0-6def-11e5-8939-68f1814000fa.png)

Some appear white on yellow, which is unreadable too:

![image](https://cloud.githubusercontent.com/assets/25395/10372343/0976c926-6df0-11e5-991a-b8a9fac08c25.png)

cc @jfirebaugh

**Comment by jfirebaugh** [comment]
Yeah, they are colored to match the console output. Yellow = passing but ignored, white = failing and ignored. But we can change the color or find some other way to indicate status.

**Comment by mourner** [comment]
@jfirebaugh or change background to black. But I'd rather adjust colors for browsers.
