### ISSUE TITLE
Update diff thresholds and ignored tests for pixelmatch 2.0.2

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-test-suite#51]
@jfirebaugh I managed to significantly improve the accuracy of anti-aliased pixels comparison algorithm in [pixelmatch](https://github.com/mapbox/pixelmatch). 

It significantly reduces false negatives (actual rendering differences that were previously detected as anti-aliasing), but now 30 tests fail in GL JS, so we probably need to update ignored tests and/or individual test diff thresholds.

Compare [pixelmatch 1 results](https://circle-artifacts.com/gh/mapbox/mapbox-gl-js/1217/artifacts/0/home/ubuntu/mapbox-gl-js/node_modules/mapbox-gl-test-suite/render-tests/index.html) vs [pixelmatch 2 results](https://circle-artifacts.com/gh/mapbox/mapbox-gl-js/1223/artifacts/0/home/ubuntu/mapbox-gl-js/node_modules/mapbox-gl-test-suite/render-tests/index.html) side by side. Examples where it detects bugs better now include `icon-halo-blur/function` and some other halo tests (halo shifts by 1px, previously ignored) and `raster-*` seams (no anti-aliasing detected so they're much more prominent),

**Comment by jfirebaugh** [comment]
⇢ #53
