### ISSUE TITLE
Map border limits

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-test-suite#59]
As per https://github.com/mapbox/mapbox-gl-native/pull/3026, we should have render tests for the given latitude coordinates:
- `(-90, -180)`
- `(-90, 180)`
- `(90, -180)`
- `(90, 190)`

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/3931
