### ISSUE TITLE
Speed up + parallelize

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-test-suite#61]
Running all tests on Travis currently takes ~3.5 minutes. We should look into ways of speeding this up and potentially parallelizing test runs and comparisons.

**Comment by mourner** [comment]
Ah, 3.5 minutes... Those were great times.

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/3930
