### ISSUE TITLE
Make it easier to find failing tests

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-test-suite#67]
The HTML page lists all tests in order, which is good for comparing different outputs, but it's hard to see which particular tests failed. We should add an index at the top linking to the failing tests.

Similarly, the console output should make failing tests more visually distinct, e.g. by uppercasing `FAILED`, and/or by listing failed tests at the end of the output. Optionally, it could replace the current line for tests that passes so that the console output isn't as long, and only retain lines that failed.

**Comment by lucaswoj** [comment]
My dream solution would be to have a toggle (that is on by default) to only display the failing tests.

**Comment by jfirebaugh** [comment]
Oh yes. :heartbeat:

**Comment by lucaswoj** [comment]
The test results page is now so big that it is unable to fully render from a CircleCI build artifact. I'm not sure what the exact bottleneck is.

**Comment by blanchg** [comment]
@lucaswoj Due to the size and number of images would you like the test harness to output the results as json and have a more static index.html that displays and loads only the selected (e.g. error and ignored) images?

Selecting to show all the results would then download and show the ok ones too.

**Comment by lucaswoj** [comment]
@blanchg I'm not attached to any particular specification. My requirements are

 - results load quickly over the slow CircleCI artifacts URL
 - finding failing tests is easy

**Comment by blanchg** [comment]
The current results page is just over 60MB as it embeds all the images to make the CI artifact exporting easier.  If we can configure the CI to publish the query and rendered test directories as described here https://circleci.com/docs/configuration/#artifacts then I have a solution that works locally and via circleci.  Is there any reason we can't make this change?  Thanks.

**Comment by lucaswoj** [comment]
No reason I'm aware of, @blanchg. This issue just hasn't come up as a top priority yet. 😄

**Comment by mourner** [comment]
> If we can configure the CI to publish the query and rendered test directories as described here

I tried this yesterday, but uploading 1.8k files as artifacts takes 7+ minutes in Circle, as opposed to 15 seconds for a single file.

I propose a compromise: split the results into 3 separate pages — passed, ignored, failed, with an index that links to the three. This way, we'll be able to instantly see failed tests because you won't have to load 60MB of non-failing results.

**Comment by kkaefer** [comment]
@mourner another minor optimization we could make is to link the original files from Github (using the commit hash) instead of encoding them into the file.

**Comment by mourner** [comment]
@kkaefer this would be a problem when working on new tests locally.

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-test-suite/issues/67
