### ISSUE TITLE
avoid shelling out to imagemagick for image comparison

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-test-suite#8]
It would be great to avoid the imagemagick dep since shelling out to `compare` can be brittle and it is easy to miss realizing it needs to be installed separately. This is why https://github.com/mapbox/assert-http#asserthttpimageequalsbuffer-buffer-options is ideal.

Happy to provide a pull if this sounds good.

**Comment by jfirebaugh** [comment]
Use https://github.com/mapbox/image-equal for this.

**Comment by jfirebaugh** [comment]
Blocked by https://github.com/mapbox/image-equal/issues/3.

**Comment by jfirebaugh** [comment]
Now using pixelmatch.
